[platform]
linux=true

[settings.browsers.chrome]
name = 'chrome'
path='/'

[settings.browsers.firefox]
name = 'firefox'
path='wd/hab'

[[settings.browsers.chrome.docker.versions]]
browser='65.0'

[[settings.browsers.firefox.docker.versions]]
browser='58.0'
