[platform]
windows=true

[settings.browsers.chrome]
name = 'chrome'
path='/'

[settings.browsers.firefox]
name = 'firefox'
path='wd/hab'

[[settings.browsers.chrome.windows.versions]]
browser = 'w65.0.3325.181'
driver = '2.37'

[[settings.browsers.chrome.windows.versions]]
browser = 'w64.0.3282.186'
driver = '2.37'

[[settings.browsers.chrome.windows.versions]]
browser = 'w63.0.3239.132'
driver = '2.37'

[[settings.browsers.firefox.windows.versions]]
browser = 'w59.0.2'
driver = '0.20.0'

[[settings.browsers.firefox.windows.versions]]
browser = 'w58.0.2'
driver = '0.20.0'

[[settings.browsers.firefox.windows.versions]]
browser = 'w57.0.4'
driver = '0.20.0'
