[settings]
port='4444'
max_sessions=10

[settings.browsers.chrome.windows]
enabled=true
versions=['65.0.3325.181']

[settings.browsers.firefox]
path='wd/hab'

[settings.browsers.chrome]
path='/'

[settings.browsers.firefox.windows]
enabled=true
versions=['59.0']
