[jenkins-service]
port = "8080"

[jenkins]
prefix = "/"

[jenkins.session]
timeout = 60

[jenkins.http]
enabled = false
port = 80

[jenkins.https]
enabled = false
port = 443

[jenkins.http2]
enabled = false
port = 80

[jenkins.ajp13]
enabled = false
port = 8009

[java]
opts = "-XX:PermSize=512M -XX:MaxPermSize=2048M -Xmn128M -Xms1024M -Xmx2048M -Djenkins.install.runSetupWizard=false"

# Groovy code to generate plugin list with versions:
# for example http://jenkins-url/script
#
# Jenkins.instance.pluginManager.plugins.each{ plugin -> println("[[jenkins-service.plugins]]\nname=\"${plugin.getShortName()}\"\nversion=\"${plugin.getVersion()}\"") }

[[jenkins-service.plugins]]
name="branch-api"
version="2.0.20"
[[jenkins-service.plugins]]
name="script-security"
version="1.44"
[[jenkins-service.plugins]]
name="command-launcher"
version="1.2"
[[jenkins-service.plugins]]
name="bouncycastle-api"
version="2.16.2"
[[jenkins-service.plugins]]
name="workflow-job"
version="2.21"
[[jenkins-service.plugins]]
name="display-url-api"
version="2.2.0"
[[jenkins-service.plugins]]
name="jackson2-api"
version="2.8.11.2"
[[jenkins-service.plugins]]
name="mailer"
version="1.21"
[[jenkins-service.plugins]]
name="icon-shim"
version="2.0.3"
[[jenkins-service.plugins]]
name="ldap"
version="1.20"
[[jenkins-service.plugins]]
name="pipeline-rest-api"
version="2.10"
[[jenkins-service.plugins]]
name="structs"
version="1.14"
[[jenkins-service.plugins]]
name="credentials"
version="2.1.16"
[[jenkins-service.plugins]]
name="ssh-credentials"
version="1.13"
[[jenkins-service.plugins]]
name="workflow-multibranch"
version="2.19"
[[jenkins-service.plugins]]
name="workflow-step-api"
version="2.15"
[[jenkins-service.plugins]]
name="antisamy-markup-formatter"
version="1.5"
[[jenkins-service.plugins]]
name="plain-credentials"
version="1.4"
[[jenkins-service.plugins]]
name="credentials-binding"
version="1.16"
[[jenkins-service.plugins]]
name="authentication-tokens"
version="1.3"
[[jenkins-service.plugins]]
name="pam-auth"
version="1.3"
[[jenkins-service.plugins]]
name="docker-commons"
version="1.13"
[[jenkins-service.plugins]]
name="scm-api"
version="2.2.7"
[[jenkins-service.plugins]]
name="filesystem_scm"
version="2.1"
[[jenkins-service.plugins]]
name="workflow-api"
version="2.27"
[[jenkins-service.plugins]]
name="junit"
version="1.24"
[[jenkins-service.plugins]]
name="matrix-project"
version="1.13"
[[jenkins-service.plugins]]
name="rebuild"
version="1.28"
[[jenkins-service.plugins]]
name="run-condition"
version="1.0"
[[jenkins-service.plugins]]
name="workflow-support"
version="2.18"
[[jenkins-service.plugins]]
name="token-macro"
version="2.5"
[[jenkins-service.plugins]]
name="build-timeout"
version="1.19"
[[jenkins-service.plugins]]
name="workflow-cps"
version="2.53"
[[jenkins-service.plugins]]
name="email-ext"
version="2.62"
[[jenkins-service.plugins]]
name="apache-httpcomponents-client-4-api"
version="4.5.5-2.1"
[[jenkins-service.plugins]]
name="jsch"
version="0.1.54.2"
[[jenkins-service.plugins]]
name="handlebars"
version="1.1.1"
[[jenkins-service.plugins]]
name="git-client"
version="2.7.2"
[[jenkins-service.plugins]]
name="git-server"
version="1.7"
[[jenkins-service.plugins]]
name="pipeline-build-step"
version="2.7"
[[jenkins-service.plugins]]
name="conditional-buildstep"
version="1.3.6"
[[jenkins-service.plugins]]
name="graphiteIntegrator"
version="1.2"
[[jenkins-service.plugins]]
name="workflow-scm-step"
version="2.6"
[[jenkins-service.plugins]]
name="momentjs"
version="1.1.1"
[[jenkins-service.plugins]]
name="mapdb-api"
version="1.0.9.0"
[[jenkins-service.plugins]]
name="subversion"
version="2.10.6"
[[jenkins-service.plugins]]
name="parameterized-trigger"
version="2.35.2"
[[jenkins-service.plugins]]
name="external-monitor-job"
version="1.7"
[[jenkins-service.plugins]]
name="cloudbees-folder"
version="6.4"
[[jenkins-service.plugins]]
name="ace-editor"
version="1.1"
[[jenkins-service.plugins]]
name="durable-task"
version="1.22"
[[jenkins-service.plugins]]
name="jquery-detached"
version="1.2.1"
[[jenkins-service.plugins]]
name="translation"
version="1.16"
[[jenkins-service.plugins]]
name="git"
version="3.9.0"
[[jenkins-service.plugins]]
name="jquery"
version="1.12.4-0"
[[jenkins-service.plugins]]
name="matrix-auth"
version="2.2"
[[jenkins-service.plugins]]
name="extended-choice-parameter"
version="0.76"
[[jenkins-service.plugins]]
name="docker-workflow"
version="1.17"
[[jenkins-service.plugins]]
name="javadoc"
version="1.4"
[[jenkins-service.plugins]]
name="maven-plugin"
version="3.1.2"
[[jenkins-service.plugins]]
name="windows-slaves"
version="1.3.1"
[[jenkins-service.plugins]]
name="ant"
version="1.8"
[[jenkins-service.plugins]]
name="pipeline-input-step"
version="2.8"
[[jenkins-service.plugins]]
name="pipeline-stage-step"
version="2.3"
[[jenkins-service.plugins]]
name="pipeline-graph-analysis"
version="1.6"
[[jenkins-service.plugins]]
name="pipeline-stage-view"
version="2.10"
[[jenkins-service.plugins]]
name="validating-string-parameter"
version="2.4"
[[jenkins-service.plugins]]
name="pipeline-milestone-step"
version="1.3.1"
[[jenkins-service.plugins]]
name="pipeline-model-api"
version="1.2.9"
[[jenkins-service.plugins]]
name="pipeline-model-extensions"
version="1.2.9"
[[jenkins-service.plugins]]
name="workflow-cps-global-lib"
version="2.9"
[[jenkins-service.plugins]]
name="workflow-durable-task-step"
version="2.19"
[[jenkins-service.plugins]]
name="workflow-basic-steps"
version="2.7"
[[jenkins-service.plugins]]
name="pipeline-stage-tags-metadata"
version="1.2.9"
[[jenkins-service.plugins]]
name="pipeline-model-declarative-agent"
version="1.1.1"
[[jenkins-service.plugins]]
name="pipeline-model-definition"
version="1.2.9"
[[jenkins-service.plugins]]
name="workflow-aggregator"
version="2.5"
[[jenkins-service.plugins]]
name="multiple-scms"
version="0.6"
[[jenkins-service.plugins]]
name="built-on-column"
version="1.1"
[[jenkins-service.plugins]]
name="ruby-runtime"
version="0.12"
[[jenkins-service.plugins]]
name="cvs"
version="2.14"
[[jenkins-service.plugins]]
name="allure-jenkins-plugin"
version="2.26.0"
[[jenkins-service.plugins]]
name="htmlpublisher"
version="1.16"
[[jenkins-service.plugins]]
name="hidden-parameter"
version="0.0.4"
[[jenkins-service.plugins]]
name="envinject-api"
version="1.5"
[[jenkins-service.plugins]]
name="envinject"
version="2.1.5"
[[jenkins-service.plugins]]
name="ssh-slaves"
version="1.26"
[[jenkins-service.plugins]]
name="jenkins-multijob-plugin"
version="1.30"
[[jenkins-service.plugins]]
name="job-dsl"
version="1.69"